alias cd..="cd .."
alias ..="cd .."
alias mkdir="mkdir -pv"
alias wget="wget -c"
alias histg="history | grep"
alias grep="grep --color=auto"
alias vpnon="expressvpn connect"
alias vpnoff="expressvpn disconnect"
alias gitmine="cd ~/git_stuff/mine/ && ls -al"
alias gityour="cd ~/git_stuff/theirs/ && ls -al"
alias suspend="sudo systemctl suspend"
alias gitp="git pull"
alias gitca="git commit -a"
alias gitps="git push"
alias sas="cp .bashrc .bash_aliases ~/ && cd ~ && . .bashrc && . .bash_aliases"
alias gohome="cd ~"
